! Even fibonacci numbers
! Each new term in the fibonacci sequence is generated by adding the previous twi terms. By starting 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
! By considering the terms in the fibonacci sequence whose values do not exceed four milion, find the sum of the even-valued terms.

program prob002
implicit none

integer :: i, i1, i2, s

i=0
i1=1
i2=2
s=0

do while (i<4000000)
    i=i1+i2
    if(mod(i,2)==0)s=s+i
    i1=i2
    i2=i
end do
print*,s

end program prob002
